# Generated by Django 3.1.7 on 2021-02-28 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleo',
            name='duracion',
            field=models.CharField(blank=True, max_length=250, verbose_name='Duración'),
        ),
        migrations.AlterField(
            model_name='empleo',
            name='salario',
            field=models.CharField(blank=True, max_length=50, verbose_name='Salario'),
        ),
        migrations.AlterField(
            model_name='empleo',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=250, verbose_name='Ubicacion'),
        ),
    ]
