# Generated by Django 3.1.7 on 2021-02-23 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0006_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='Categories',
            field=models.ManyToManyField(blank=True, related_name='articulos', to='proyectos.Categoria', verbose_name='Categorias'),
        ),
    ]
