# Generated by Django 3.1.7 on 2021-02-21 18:44

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Titulo')),
                ('year', models.IntegerField(verbose_name='Año')),
                ('resumen', models.CharField(max_length=150, verbose_name='Resumen')),
                ('descripcion', ckeditor.fields.RichTextField(blank=True, verbose_name='Descripcion')),
                ('imagen', models.ImageField(blank=True, upload_to=None)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
            },
        ),
    ]
