# Generated by Django 3.1.7 on 2021-03-09 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0008_auto_20210228_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='resumen',
            field=models.CharField(max_length=250, verbose_name='Resumen'),
        ),
    ]
