# Generated by Django 3.1.7 on 2021-03-15 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0011_auto_20210311_1556'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foto',
            options={'verbose_name': 'Foto', 'verbose_name_plural': 'Fotos'},
        ),
    ]
